kind: Simple
#which version of k3d is used
apiVersion: k3d.io/v1alpha3
#name of the cluster
name: my-cluster
#which version of k8s is used
image: rancher/k3s:v1.22.7-k3s1
#how many server / master nodes
servers: 1
#how many agent / worker nodes
agents: 2
# map ports, here we map 
ports:
- port: 80:80
  nodeFilters:
  - loadbalancer

